spring:
  datasource:
    name: buslines
    url: jdbc:mysql://39.96.15.89:3306/buslines
    username: root
    password: Ivy161420
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.example.busline.bean

server:
  port: 8080